svelte binary modifications

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,26 +19,29 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '14'  # Adjust as needed
+          node-version: '14'
 
       - name: Install Dependencies
         run: npm install
 
-      - name: Install pkg
-        run: npm install -g pkg
-
       - name: Build Svelte App
         run: npm run build
 
-      - name: Package Svelte App
-        run: npm run package
+      - name: Confirm Build Output
+        run: |
+          if [ -f ./my-svelte-app.exe ]; then
+            echo "File exists: my-svelte-app.exe"
+          else
+            echo "Error: my-svelte-app.exe file not found"
+            exit 1
+          fi
+
+      - name: Install AWS CLI
+        run: |
+          npm install -g aws-cli
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: 'ap-southeast-1'
+        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ap-southeast-1
 
       - name: Upload Binary to S3
-        run: aws s3 cp ./dist/my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.sha }}/my-svelte-app.exe --acl public-read
+        run: aws s3 cp ./my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.sha }}/my-svelte-app.exe --acl public-read
