svelte binary modifications

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,21 +27,21 @@ jobs:
       - name: Build Svelte App
         run: npm run build
 
-      - name: Install pkg
-        run: npm install -g pkg
-
-      - name: Package Svelte App
-        run: npm run package
-
       - name: Confirm Build Output
-        run: ls -l ./dist/hrmadminportal.exe
+        run: |
+          if [ -f ./dist/hrmadminportal.exe ]; then
+            echo "File exists: hrmadminportal.exe"
+          else
+            echo "Error: hrmadminportal.exe file not found"
+            exit 1
+          fi
+
+      - name: Install AWS CLI
+        run: |
+          npm install -g aws-cli
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: 'ap-southeast-1'
+        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ap-southeast-1
 
       - name: Upload Binary to S3
         run: aws s3 cp ./dist/hrmadminportal.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.sha }}/hrmadminportal.exe --acl public-read
